services:
  host: localhost
  port: 8080

database:
  read:
    driver: postgresql
    host: localhost
    port: 5432
    database: inventory
    schema: inventory
    username: ryuze
    password: asd123qwe
  write:
    driver: postgresql
    host: localhost
    port: 5432
    database: inventory
    schema: inventory
    username: ryuze
    password: asd123qwe